runtime: nodejs16
env: standard
instance_class: F1
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)
automatic_scaling:
  min_instances: 1
  max_instances: 3
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 5000ms
  max_pending_latency: 10000ms
  max_concurrent_requests: 80
